
stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy

cache:
  key: npm
  policy: pull-push
  paths:
    - .npm/
    - build/

##
#frontend
##

test_frontend:
  stage: test
  image: node:slim
  script:
    - echo "Test frontend"
    - npm ci --cache .npm --prefer-offline
    - CI=true npm test

build_frontend:
  stage: build
  image: node:slim
  script:
    - echo "Build frontend"
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - ls build

deploy_frontend:
   stage: deploy
   script:
#     - echo "Deploy"
    - apk update && apk add rsync openssh curl
    # Prepare SSH settings
    - mkdir -p ~/.ssh && (umask  077 ; echo "${DEPLOY_KEY_PRIVATE}" | base64 -d > ~/.ssh/id_rsa)
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    # Transfer to server
    - rsync -r . "deploy@172.16.6.213:/home/deploy/app"
    # Run commands on the server
    - ssh deploy@172.16.6.213 /bin/bash
            "
            echo 'Starting..';
            cd ~/app;
            docker build -t greenapp .;
            docker run -d --name greenapp_container -p 3000:3000 greenapp;
            "

##
#backend
##

test_backend:
  stage: test
  script:
    - echo "Test"

build_backend:
  stage: build
  script:
    - echo "Build"

deploy_backend:
  stage: deploy
  script:
    - echo "Deploy"
