stages:
  - test
  - build
  - deploy
 
variables:
  REACT_APP_API_URL: "https://23fullstack05.course.tamk.cloud"  # Replace with your API server URL
 
test_job:
  stage: test
  script:
    - docker run -v $(pwd):/app -w /app node:14 npm install
    - docker run -v $(pwd):/app -w /app node:14 npm test
 
build_job:
  stage: build
  script:
    - docker run -v $(pwd):/app -w /app node:14 npm install
    - docker run -v $(pwd):/app -w /app node:14 npm run build
  artifacts:
    paths:
      - build/
 
deploy_job:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y sshpass
    - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no -r build/* $SSH_USER@$SSH_HOST:/path/to/your/deployment/directory
  only:
    - main
